# Generated by Django 3.2.5 on 2021-11-17 12:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ani_image/')),
                ('left_right', models.CharField(choices=[('좌', '좌->우'), ('우', '우->좌')], default='좌', max_length=5)),
                ('ani', models.FileField(blank=True, null=True, upload_to='ani/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['avi', 'mp4', 'mkv', 'mpeg', 'webm'])])),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='ani_image/')),
                ('image_base64', models.TextField(blank=True, null=True)),
                ('animate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ani_id', to='animateapp.animate')),
            ],
        ),
    ]
