# Generated by Django 3.2.5 on 2021-11-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateapp', '0002_alter_animate_ani'),
    ]

    operations = [
        migrations.AddField(
            model_name='animate',
            name='ani_effect',
            field=models.CharField(choices=[('B', '말풍선'), ('N', '없음')], default='N', max_length=5),
        ),
        migrations.AddField(
            model_name='animate',
            name='toon_comic',
            field=models.CharField(choices=[('T', '웹툰 형식'), ('C', '만화책형식')], default='T', max_length=5),
        ),
        migrations.AddField(
            model_name='animate',
            name='transition_effect',
            field=models.CharField(choices=[('D', '디졸브'), ('U', '위로 슬라이드'), ('Lt', '왼쪽으로 슬라이드'), ('Rt', '오른쪽으로 슬라이드'), ('N', '없음')], default='N', max_length=5),
        ),
        migrations.AddField(
            model_name='animateimage',
            name='ani_effect',
            field=models.CharField(default='N', max_length=5),
        ),
        migrations.AddField(
            model_name='animateimage',
            name='left_right',
            field=models.CharField(default='L', max_length=5),
        ),
        migrations.AddField(
            model_name='animateimage',
            name='toon_comic',
            field=models.CharField(default='T', max_length=5),
        ),
        migrations.AddField(
            model_name='animateimage',
            name='transition_effect',
            field=models.CharField(default='N', max_length=5),
        ),
    ]
